### PR TITLE
download and load font-awesome locally ( first-timers-only ) #66

### PR DESCRIPTION
**Pull request by mtochi**
font-awesome downloaded and put in src/static/css and the path updated

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by cg-cnu** [comment]
Hey @mtochi Please don't mix multiple commits in one pr. And please try to solve only one first-timer issue. Hope you understand, Thanks!

**Comment by mtochi** [comment]
Hey @cg-cnu, should I undo the 2nd first time issue?
ps. I'm really sorry for causing any incovenience.

**Comment by cg-cnu** [comment]
Hey @mtochi Yes please. You can work on https://github.com/DAVFoundation/xplore/issues/66 and keep the commits needed to address that. Thanks for understanding 🙂

**Comment by cg-cnu** [comment]
Hey @mtochi would you mind cleaning up the commits and finish off the pr for downloading `font-awesome` locally ?

**Comment by cg-cnu** [comment]
Hey @mtochi am closing this pr and assigning it to someone else. Please feel free to claim and work on some other issues. Hope to see you around 🙂

**Pull request closed without merging**
