### PR TITLE
#95 Changed RPC component's background color

### PR DESCRIPTION
**Pull request by edxds**
## Description
Changed the RPC component's background color/gradient as described in issue #95 

## Screenshots (if appropriate):
pr_fixed

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by cg-cnu** [comment]
Hey @edxds can you compare the background gradient with the one shown in the mockup and fix it ? Right now its just a single plain color. 🙂

**Comment by edxds** [comment]
Done!

**Comment by cg-cnu** [comment]
Hey @edxds I think there is a serious miscommunication going on here...

Let me explain clearly, you are working on this issue https://github.com/DAVFoundation/xplore/issues/95 which deals with fixing the background color of the **RPC Component**. 

Which means you are supposed to change the background color of the **RPC Component** from this...
image
to this...
image
by changing the css values. 

Would you mind fixing it and creating one more pr ? Thanks! Let me know if you have any questions. You are almost there, lets wrap this one up! 😄

**Comment by cg-cnu** [comment]
Hey @edxds We have changed the design of xplore app and this PR is no longer valid. Am sorry, but we have to close this PR. I will be creating more first-timer issues soon. Please feel free to pickup any of them. Thanks 🙂

**Pull request closed without merging**
