### PR TITLE
extracted url to a variable

### PR DESCRIPTION
**Pull request by cg-cnu**
## Description

Extracted url to a separate variable. @TalAter Let me know if you have a better variable name for it. 

## Motivation and Context

Will create a first-timer issue to move the url to the config file once this is approved. Thanks!

## How Has This Been Tested?

npm test is successful!

### CODE REVIEW

**Comment by cg-cnu** [comment]
Hey @TalAter Just let me know if the variable name `url` is ok! I will fix the conflict with the other pr in a bit.

**Review by TalAter — APPROVED** [review]
Looks good. But there's a conflict that needs to be resolved first.

**Comment by cg-cnu** [comment]
Thanks! I will resolve it.

**Comment by cg-cnu** [comment]
@TalAter Fixed the conflict. Will create the first-timer issue after its merged. Thanks!

**Comment by cg-cnu** [comment]
Hey @TalAter Merging the pr as its working fine.

**Pull request merged**
