### PR TITLE
Fixed: Added screenshot of Xplore to readme.md #69

### PR DESCRIPTION
**Pull request by mrcolo**
## Description
Added screenshot of Xplore to readme.md #69

## Motivation and Context
solved issue #69 

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by TalAter** [comment]
Thank you for the help @mrcolo 👍

A few comments:

1. Can you remove the changes done to the `package-lock.json`. Those have nothing to do with this issue.
2. Can you make the screenshot aligned to the right next to the text as shown on on https://github.com/DAVFoundation/missioncontrol/blob/master/README.md
3. Can you replace the screenshot with this one I just took (which includes some data)

readme

Thank you

**Comment by mrcolo** [comment]
Yes @TalAter , I'll make sure to commit the changes by tonight! 

For the screenshot, could you attach an image with better quality? That one has a very small size and it's hard to read.

**Comment by TalAter** [comment]
The idea isn't for people to be able to read what's in there, it's only there to give them an idea of what it is.

**Comment by mrcolo** [comment]
Okay, I changed the files. I apologize for the misunderstanding. I'm very new to opensource. Please, let me know if you guys need help with anything help, I really appreciate your advices!

**Comment by TalAter** [comment]
No problem.

Can you also undo the changes to `package-lock.json`? If this is too much of a hassle, you can just close this pr, and create a new one with just the changes to README and the image.

**Comment by mrcolo** [comment]
done. hope it's okay now.

**Comment by cg-cnu** [comment]
Hey @mrcolo We have changed the design of the `xplore` app. So, this pr is no longer valid. Sorry, but am closing this PR for clarity. I Will keep creating more first-timers issues soon. Please feel free to pickup any of them. Thanks for your time 🙂

**Pull request closed without merging**
