### PR TITLE
download and load google fonts locally #67

### PR DESCRIPTION
**Pull request by mohinderps**
Dowloaded the fonts using npm module google-fonts-offline and put the fonts in static/fonts folder. Updated index.html to load the fonts before loading styles.css

## Description

1. Downloaded the fonts using npm module google-fonts-locally.
2. Created a folder static/fonts. Added all the fonts to this folder and a fonts.css file.
3. Updated index.html to loaded static/fonts/fonts.css file before loading styles/style.css file so that the downloaded fonts are available to use.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by cg-cnu** [comment]
Hey @mohinderps There is a conflict in the pr because of another fix. Would you mind pulling the latest changes and fixing the conflic. Thanks!

**Comment by mohinderps** [comment]
Hey @cg-cnu, I have resolved the conflict and updated the PR.

**Comment by cg-cnu** [comment]
Hey @srfrnk can you please review this. Thanks! 🙂

**Comment by mohinderps** [comment]
Hey @srfrnk can you please review this. Thanks!

**Pull request closed without merging**
